### ISSUE TITLE
New  install on Debian Buster - Sense Node Server errors

### ISSUE THREAD

**Issue by dwengrovitz** [therealmysteryman/udi-sense-monitoring-polyglot#6]
I did a clean installation of Debian 10 on a new RPI 4.  Installed Polyglot and the SenseMonitoring node server (directly from the Polyglot NodeServer Store).  The SenseMonitoring node server seems to detect my Sense devices correctly, and they are being populated in the ISY admin console.  But I don't seem to get any device or energy usage updates.  The SenseMonitoring log in Polyglot is showing recurring errors like the one below every minute or so. 

2019-08-09 20:38:26,435 [Controller] [ERROR] query, unable to retrieve Sense Monitor usage: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1056)

My other Polyglot node servers, such as Ring, Nest, etc., seem to be working okay.  Any idea what might be going on with the SenseMonitoring node?

**Comment by therealmysteryman** [comment]
It related to newer version of OpenSSL not supporting the TLS 1.1 required by the Sense API. There is a workarround that could be implemented by changing some code in sensable package. [https://github.com/scottbonline/sense/issues/30#issuecomment-508319366](url)
